name: flutter_pdfview
description: A Flutter plugin that provides a PDFView widget on Android and iOS.
version: 1.3.1
homepage: https://github.com/endigo/flutter_pdfview

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.endigo.plugins.pdfviewflutter
        pluginClass: PDFViewFlutterPlugin
      ios:
        pluginClass: FLTPDFViewFlutterPlugin
